global:

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  group_by:
    - alertname
    - environment

  group_wait: 30s
  group_interval: 5m

  repeat_interval: 1m

  receiver: webhook


receivers:
  - name: webhook
    webhook_configs:
      - url: "http://localhost:5000/alerts/handle"
