name: Python

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Python

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: pyproject.toml

      - name: Build
        run: uv sync --all-extras --dev

      - name: Test
        run: make check

  docker:
    runs-on: ubuntu-latest
    name: Test Docker build

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Docker build
        run: docker build .
