name: Python

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Python

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version-file: pyproject.toml

      - name: Build
        run: uv sync --all-extras --dev

      - name: Test
        run: make check

  docker:
    runs-on: ubuntu-latest
    name: Test Docker build

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Docker build
        run: docker build .
